# Generated by Django 5.2 on 2025-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_itemsolicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoenvio',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
